title: Emma's Website
author: Emma Buttars
description: >- # this means to ignore newlines until "baseurl:"
  This is a website for Emma Buttars. I am doing this for my CS 1030 class so that I can learn how to teach it in a high school."
baseurl: "my-first-website-SuperBuckoSchool" # the subpath of your site, e.g. /blog
logo: "/assets/images/my_sim.png"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
